# Generated by Django 3.1.6 on 2022-02-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('SupervisorId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=10)),
                ('Lastname', models.CharField(max_length=10)),
                ('Hourly_rate', models.IntegerField()),
                ('TeamName', models.CharField(max_length=10)),
                ('TeamAvg_HandleTime', models.FloatField(default=0)),
                ('TeamAvg_Cx_rating', models.FloatField(default=0)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Empid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=10)),
                ('Lastname', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('Avg_HandleTime', models.FloatField(default=0)),
                ('Avg_Cx_rating', models.FloatField(default=0)),
                ('Total_Chats', models.IntegerField(default=0)),
                ('Hourly_rate', models.IntegerField(default=0)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDash.supervisor')),
            ],
        ),
    ]
